-- Mark all remaining modules as available and align Financial & Crypto scoring with the wireframe quiz (3 x 250 = 750).
update public.modules set status = 'available' where slug in ('passwords-2fa','malware-ransomware','vishing-smishing','physical-travel','data-compliance','social-engineering','financial-crypto');
update public.modules set max_points = 750, pass_threshold = 525 where slug = 'financial-crypto';

-- Passwords & 2FA -----------------------------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'Beyond ''password123''','A strong password is your first and most crucial line of defense. Attackers use automated software to guess millions of passwords per second. Simple, common, or personal passwords can be cracked almost instantly.','[]' from public.modules where slug='passwords-2fa';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'The Pillars of a Strong Password','["Length is Strength: Aim for at least 14 characters. Each additional character makes a password exponentially harder to crack.","Complexity is Key: Use a mix of uppercase letters, lowercase letters, numbers, and symbols (e.g., !@#$%).","Uniqueness is Non-Negotiable: Never reuse passwords across different websites. A breach on one site would expose all your accounts."]' from public.modules where slug='passwords-2fa';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'Your Secret Weapon: The Password Manager','It''s impossible to remember dozens of unique, complex passwords. A trusted password manager solves this. It generates, stores, and auto-fills ultra-strong passwords for you, so you only need to remember one master password.','[]' from public.modules where slug='passwords-2fa';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,4,'Two-Factor Authentication (2FA/MFA)','2FA is a security force multiplier. It requires a second form of verification (like a code from your phone) besides your password. This means even if an attacker steals your password, they cannot get into your account. Enable it everywhere.','[]' from public.modules where slug='passwords-2fa';

with m as (select id from public.modules where slug='passwords-2fa')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'password-manager',1,'What is the most effective way to manage unique, complex passwords for all your accounts?','Password managers are designed to securely create, store, and manage unique and strong passwords for every account, eliminating password reuse and the need to remember them all.','Password management',150 from m
union all select id,'strong-password',2,'Which password example follows best practices for strength and uniqueness?','''aPpLePi3&C0ff33!'' is a strong passphrase that is long, complex, and avoids common patterns, making it highly resistant to cracking. The others use common patterns or are too short/simple.','Password strength',150 from m
union all select id,'weakest-password',3,'Which of the following is the WEAKEST password?','''Summer2024!'' is predictable and follows a common pattern (word + year + symbol), making it much easier to guess with automated tools than a truly random string of characters.','Password strength',100 from m
union all select id,'2fa-benefit',4,'What is the primary benefit of Two-Factor Authentication (2FA)?','2FA''s main strength is that it requires a second factor (something you have, like your phone) in addition to your password (something you know), stopping attackers who have only stolen the password.','2FA',150 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'notebook',1,'Write them down in a notebook',false),(1,'manager',2,'Use a trusted password manager application',true),(1,'monthly',3,'Use the same password everywhere but change it monthly',false),(1,'pet-name',4,'Use variations of your pet''s name',false),
(2,'yourcompany',1,'YourCompany123',false),(2,'passwordforwork',2,'P@ssword ForWork!',false),(2,'applepi',3,'aPpLePi3&C0ff33!',true),(2,'qwerty',4,'QwertY@123',false),
(3,'random',1,'Fg#9k$2(j@1Po!',false),(3,'summer',2,'Summer2024!',true),(3,'dogname',3,'MyDogFido123',false),(3,'troubadour',4,'Tr0ub4dor&3',false),
(4,'stronger-password',1,'It makes your password stronger',false),(4,'prevents-theft',2,'It prevents your password from being stolen',false),(4,'second-layer',3,'It adds a second layer of security, making your account inaccessible even if your password is stolen',true),(4,'auto-login',4,'It automatically logs you into your accounts',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='passwords-2fa';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Use a password manager to create unique passwords for every service.' from public.modules where slug='passwords-2fa'
union all select id,2,'Enable Two-Factor Authentication (2FA) on all critical accounts.' from public.modules where slug='passwords-2fa'
union all select id,3,'Make passwords long (14+ characters) and complex (mix of cases, numbers, symbols).' from public.modules where slug='passwords-2fa'
union all select id,4,'Never reuse passwords. A breach on one site will compromise others.' from public.modules where slug='passwords-2fa';

-- Malware & Ransomware Defense ----------------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'Understanding Malicious Software','Malware is any software designed to harm your system. It includes viruses, spyware, and trojans. Ransomware is a particularly nasty type that encrypts all your files, holding them hostage until you pay a fee.','[]' from public.modules where slug='malware-ransomware';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'Common Infection Vectors','["Phishing Emails: Clicking malicious links or opening infected attachments is the #1 way malware spreads.","Malicious Downloads: Software from untrusted websites, often disguised as ''free'' games or utilities, can be bundled with malware.","Unpatched Software: Attackers exploit security holes in outdated software (your OS, browser, or applications). Keeping everything updated is critical."]' from public.modules where slug='malware-ransomware';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'Your Defensive Strategy','A multi-layered defense is key. Use a reputable antivirus/anti-malware program and keep it updated. Be extremely cautious about what you click and download. Regularly back up your important files to an external drive or cloud service; this is your best defense against ransomware.','[]' from public.modules where slug='malware-ransomware';

with m as (select id from public.modules where slug='malware-ransomware')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'ransomware-definition',1,'What is the defining characteristic of a ransomware attack?','Ransomware''s goal is extortion. It makes your files unusable by encrypting them and then demands a ransom payment, usually in cryptocurrency, for the decryption key.','Ransomware',200 from m
union all select id,'software-updates',2,'Why is it crucial to keep your operating system and applications updated?','Software updates frequently include patches for security holes that have been discovered. Attackers specifically target these known vulnerabilities in outdated software to deliver malware.','Patching',100 from m
union all select id,'ransomware-recovery',3,'What is the single most effective way to recover from a ransomware attack without paying the ransom?','If you have clean backups, you can restore your files without needing to pay the attackers. This neutralizes their primary leverage and is a critical part of any security strategy.','Ransomware recovery',200 from m
union all select id,'malware-vectors',4,'Which of these is NOT a common way malware can infect a computer?','Official software updates from trusted vendors are designed to fix security flaws and add features, not introduce malware. Malware typically spreads through malicious downloads, phishing, or exploiting vulnerabilities.','Malware vectors',150 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'steals-password',1,'It steals your password',false),(1,'slows-down',2,'It slows down your computer',false),(1,'encrypts-files',3,'It encrypts your files and demands a payment for their release',true),(1,'popups',4,'It displays unwanted pop-up ads',false),
(2,'new-features',1,'To get new features and a better user interface',false),(2,'fix-vulnerabilities',2,'To fix security vulnerabilities that malware can exploit',true),(2,'compatibility',3,'To ensure compatibility with new websites',false),(2,'faster',4,'To make your software run faster',false),
(3,'unplug',1,'Unplugging your computer from the internet',false),(3,'scan-after',2,'Running an antivirus scan after the attack',false),(3,'backups',3,'Having recent, secure backups of your important files',true),(3,'negotiate',4,'Negotiating with the attackers for a lower price',false),
(4,'official-updates',1,'Through official software updates from trusted vendors',true),(4,'phishing-links',2,'By clicking malicious links in phishing emails',false),(4,'cracked-software',3,'Downloading cracked software from untrusted websites',false),(4,'exploit-vuln',4,'Exploiting security vulnerabilities in outdated software',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='malware-ransomware';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Ransomware encrypts your files and demands payment; backups are your best defense.' from public.modules where slug='malware-ransomware'
union all select id,2,'Keep your operating system, browser, and all applications fully updated.' from public.modules where slug='malware-ransomware'
union all select id,3,'Use a reputable antivirus program and keep its definitions current.' from public.modules where slug='malware-ransomware'
union all select id,4,'Be highly suspicious of unsolicited email attachments and downloads from untrusted sites.' from public.modules where slug='malware-ransomware';

-- Vishing & Smishing ----------------------------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'Phishing Beyond Email','Social engineering doesn''t just happen in your inbox. Attackers also use phone calls and text messages to trick you. This is known as Vishing (Voice Phishing) and Smishing (SMS Phishing).','[]' from public.modules where slug='vishing-smishing';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'Common Scams and Tactics','["Urgent Bank Alerts (Smishing): A text message claims your account is frozen and provides a link to ''verify'' your identity. The link leads to a fake login page.","Tech Support Scams (Vishing): An unsolicited call from someone claiming to be from Microsoft or Apple, stating your computer is infected. They aim to get remote access or payment.","Impersonation: Attackers may pretend to be from the IRS, a delivery service, or even your own company''s IT helpdesk."]' from public.modules where slug='vishing-smishing';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'How to Respond','The golden rule is: Never trust, always verify. Do not click links in suspicious texts. Hang up on unsolicited calls. If the message claims to be from a company you do business with, contact them directly using a phone number or website you know is legitimate. Never use the contact info provided in the message or call.','[]' from public.modules where slug='vishing-smishing';

with m as (select id from public.modules where slug='vishing-smishing')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'smishing-link',1,'You receive a text message from an unknown number that says: ''Your bank account has been locked due to suspicious activity. Click here to unlock it: [link]''. What should you do?','This is a classic smishing tactic. The link leads to a fake site designed to steal your login credentials. Always verify such claims by contacting the institution through an official, trusted channel you find yourself.','Smishing',200 from m
union all select id,'tech-support-call',2,'A person calls you claiming to be from ''Microsoft Tech Support'' and says they''ve detected a virus on your computer. They ask to remotely access your machine. You should:','Legitimate tech support from companies like Microsoft or Apple will never call you unsolicited. This is a scam to gain control of your computer, steal data, or install malware. The only safe action is to hang up.','Vishing',200 from m
union all select id,'phishing-vishing-smishing',3,'What is the key difference between Phishing, Vishing, and Smishing?','They are all forms of social engineering designed to trick you. The only difference is the communication channel used: Phishing (email), Vishing (voice), and Smishing (SMS).','Definitions',150 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'click-link',1,'Click the link immediately to secure your account',false),(1,'reply-stop',2,'Reply ''STOP'' to the text message',false),(1,'official-app',3,'Delete the message and contact your bank using their official website or app',true),(1,'call-back',4,'Call the phone number the text came from',false),
(2,'follow-instructions',1,'Follow their instructions, as Microsoft is a trusted company',false),(2,'ask-id',2,'Ask for their employee ID number to verify them',false),(2,'hang-up',3,'Politely hang up the phone',true),(2,'give-ip',4,'Give them your IP address so they can run a scan',false),
(3,'info-type',1,'The type of information they try to steal',false),(3,'country',2,'The country they originate from',false),(3,'medium',3,'The medium they use: email, voice call, or SMS text message',true),(3,'danger-level',4,'The level of danger they pose',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='vishing-smishing';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Vishing = Voice Phishing (scams via phone calls).' from public.modules where slug='vishing-smishing'
union all select id,2,'Smishing = SMS Phishing (scams via text messages).' from public.modules where slug='vishing-smishing'
union all select id,3,'Never click links or call numbers from unsolicited texts or calls.' from public.modules where slug='vishing-smishing'
union all select id,4,'Verify any urgent request by contacting the company through their official website or phone number.' from public.modules where slug='vishing-smishing';

-- Physical, Travel, & Remote Security -----------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'Security is Not Just Digital','Protecting information goes beyond firewalls. Physical security means protecting your devices and your screen from unauthorized access in the real world.','[]' from public.modules where slug='physical-travel';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'In the Office and On the Go','["Lock Your Screen: Always lock your computer when you step away, even for a moment. (Win+L on Windows, Cmd+Ctrl+Q on Mac).","Beware of Shoulder Surfing: Be aware of your surroundings in public places like cafes or airports. People can watch you enter passwords or view sensitive data over your shoulder.","Secure Your Devices: Never leave laptops, phones, or tablets unattended in public. When traveling, keep them in your possession, not in checked luggage."]' from public.modules where slug='physical-travel';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'The Dangers of Public Wi-Fi','Public Wi-Fi is not secure. Attackers on the same network can potentially intercept your data. Avoid logging into sensitive accounts (bank, email) on public Wi-Fi. If you must use it, always use a trusted Virtual Private Network (VPN) to encrypt your connection.','[]' from public.modules where slug='physical-travel';

with m as (select id from public.modules where slug='physical-travel')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'shoulder-surfing',1,'What is ''shoulder surfing''?','Shoulder surfing is a low-tech but effective method of stealing confidential information, like passwords or PINs, by simply looking over someone''s shoulder.','Physical security',200 from m
union all select id,'public-wifi',2,'When working in a public coffee shop, what is the best way to protect your data on their Wi-Fi network?','While HTTPS is good, a VPN is the most comprehensive solution. It encrypts ALL your internet traffic, creating a secure tunnel that prevents anyone on the same network from snooping on your activity.','Public Wi-Fi',200 from m
union all select id,'lock-shortcut',3,'What is the keyboard shortcut to quickly lock your computer screen on Windows?','Windows Key + L is the fastest way to lock your screen, a critical habit to build whenever you step away from your desk to prevent unauthorized physical access.','Device security',200 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'browsing-technique',1,'A new web browsing technique',false),(1,'screen-protector',2,'Using a screen protector to block side views',false),(1,'observing-screen',3,'The act of observing someone''s screen or keyboard to steal information',true),(1,'malware-watch',4,'A type of malware that watches your screen',false),
(2,'https-only',1,'Only visit websites that use HTTPS',false),(2,'vpn',2,'Use a Virtual Private Network (VPN)',true),(2,'ask-barista',3,'Ask the barista if the Wi-Fi is secure',false),(2,'short-connection',4,'Connect only for a few minutes at a time',false),
(3,'ctrl-alt-del',1,'Ctrl + Alt + Delete',false),(3,'alt-f4',2,'Alt + F4',false),(3,'win-l',3,'Windows Key + L',true),(3,'ctrl-l',4,'Ctrl + L',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='physical-travel';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Always lock your computer when you step away (Win+L or Cmd+Ctrl+Q).' from public.modules where slug='physical-travel'
union all select id,2,'Use a VPN to encrypt your connection on public Wi-Fi networks.' from public.modules where slug='physical-travel'
union all select id,3,'Be aware of ''shoulder surfers'' watching your screen in public places.' from public.modules where slug='physical-travel'
union all select id,4,'Never leave devices like laptops or phones unattended.' from public.modules where slug='physical-travel';

-- Data Handling, Reporting, & Compliance ---------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'Not All Data is Equal','Data is often classified by its sensitivity: Public (press releases), Internal (org charts), and Confidential/Restricted (personally identifiable information (PII), financial records, health information). You have a responsibility to protect sensitive data.','[]' from public.modules where slug='data-compliance';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'Secure Handling and Disposal','["Need to Know: Only access and share sensitive data with those who have a legitimate business need.","Secure Storage: Store confidential data on approved, encrypted systems, not on personal devices or unsecured cloud services.","Proper Disposal: Don''t just throw sensitive information away. Physical documents should be shredded. Digital files should be securely deleted, not just moved to the trash bin."]' from public.modules where slug='data-compliance';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'When Things Go Wrong: Incident Reporting','If you suspect a security incident (e.g., you clicked a phishing link, lost a work device, or see suspicious activity), you must report it immediately to the designated contact (IT, InfoSec, your manager). Fast reporting is critical to minimizing damage.','[]' from public.modules where slug='data-compliance';

with m as (select id from public.modules where slug='data-compliance')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'pii-classification',1,'An employee''s home address and phone number is an example of what kind of data?','PII is any data that can be used to identify a specific individual. It''s considered sensitive, confidential data and must be protected to prevent identity theft and privacy violations.','Data classification',250 from m
union all select id,'document-disposal',2,'What is the correct way to dispose of a printed document containing confidential client information?','Simply throwing away sensitive documents can lead to ''dumpster diving'' attacks. A cross-cut shredder makes the documents extremely difficult to reconstruct, which is the standard for secure disposal.','Data disposal',250 from m
union all select id,'incident-reporting',3,'You realize you accidentally clicked a link in a suspicious email. What is the most important first step?','Time is critical during a potential breach. Your security team has tools and procedures to investigate and contain threats, but they need to know as soon as possible. Reporting quickly is the most responsible action.','Incident reporting',200 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'public',1,'Public',false),(1,'internal',2,'Internal',false),(1,'pii',3,'Confidential / Personally Identifiable Information (PII)',true),(1,'trivial',4,'Trivial',false),
(2,'tear-recycle',1,'Tear it in half and put it in the recycling bin',false),(2,'regular-trash',2,'Put it in the regular trash can',false),(2,'shredder',3,'Use a cross-cut shredder',true),(2,'leave-desk',4,'Leave it on your desk for the cleaning crew to handle',false),
(3,'antivirus-scan',1,'Immediately run an antivirus scan',false),(3,'turn-off',2,'Turn off your computer and hope for the best',false),(3,'tell-no-one',3,'Don''t tell anyone to avoid getting in trouble',false),(3,'report-it',4,'Immediately report the incident to your IT/Security department',true)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='data-compliance';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Classify data based on sensitivity (Public, Internal, Confidential).' from public.modules where slug='data-compliance'
union all select id,2,'Handle confidential data with care and only share on a ''need-to-know'' basis.' from public.modules where slug='data-compliance'
union all select id,3,'Securely dispose of sensitive data by shredding physical documents.' from public.modules where slug='data-compliance'
union all select id,4,'Report any suspected security incident to your IT/Security team IMMEDIATELY.' from public.modules where slug='data-compliance';

-- Social Engineering & Modern Scams ---------------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'The Human Element','Social engineering is the art of manipulating people so they give up confidential information. Attackers know that humans are often the weakest link in the security chain.','[]' from public.modules where slug='social-engineering';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'Modern Scam Tactics','["CEO Fraud / Business Email Compromise (BEC): An attacker impersonates a high-level executive (like the CEO) and emails an employee, usually in finance, urgently requesting a wire transfer or sensitive data.","Deepfakes & AI Voice Cloning: Scammers use AI to clone the voice of a loved one or an executive, calling to demand immediate financial assistance or authorize transactions.","Baiting & Quid Pro Quo: Leaving an infected USB drive in a parking lot (baiting) or offering a fake benefit in exchange for information (quid pro quo).","Pretexting: Creating a fabricated scenario (a pretext) to steal personal information, such as pretending to be a survey researcher or a bank official."]' from public.modules where slug='social-engineering';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'Defending Against Manipulation','Always verify unusual requests, especially those involving money or sensitive data, through a secondary channel. If the ''CEO'' emails you for an urgent wire transfer, call them or speak to them in person to confirm. Be skeptical of unsolicited offers and never plug in unknown devices.','[]' from public.modules where slug='social-engineering';

with m as (select id from public.modules where slug='social-engineering')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'pretexting-goal',1,'What is the primary goal of a ''pretexting'' attack?','Pretexting involves an attacker inventing a scenario (the pretext) to engage a victim and increase the chance they will divulge information or perform actions that would be unlikely in ordinary circumstances.','Pretexting',250 from m
union all select id,'usb-found',2,'You find a USB drive in the company parking lot. What is the safest course of action?','This is a ''baiting'' attack. The USB drive could be loaded with malware that will infect any computer it''s plugged into. IT/Security has safe ways to examine such devices.','Baiting',250 from m
union all select id,'ceo-wire-transfer',3,'You receive an urgent email from your company''s CEO asking you to immediately wire $50,000 to a new vendor. The email address looks correct. What should you do?','This is a classic Business Email Compromise (BEC) scenario. Always verify unusual or urgent financial requests through a secondary, trusted communication channel (like a phone call or in-person conversation) before taking action.','BEC',250 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'ransomware',1,'To infect your computer with ransomware',false),(1,'fabricated-scenario',2,'To create a fabricated scenario to trick you into revealing sensitive information',true),(1,'guess-password',3,'To guess your password using automated tools',false),(1,'steal-laptop',4,'To physically steal your laptop',false),
(2,'plug-own',1,'Plug it into your computer to see who it belongs to so you can return it',false),(2,'plug-public',2,'Plug it into a public computer at a library to check its contents safely',false),(2,'trash',3,'Throw it in the trash',false),(2,'give-it',4,'Give it to your IT or Security department',true),
(3,'process-transfer',1,'Process the wire transfer immediately to avoid upsetting the CEO',false),(3,'reply-invoice',2,'Reply to the email asking for the invoice',false),(3,'verify-secondary',3,'Call the CEO or speak to them in person to verify the request',true),(3,'forward-finance',4,'Forward the email to the finance department to handle',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='social-engineering';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Verify urgent financial requests from executives via a secondary channel (e.g., phone call).' from public.modules where slug='social-engineering'
union all select id,2,'Be aware that AI can now clone voices and create convincing deepfakes.' from public.modules where slug='social-engineering'
union all select id,3,'Never plug unknown USB drives or devices into your computer.' from public.modules where slug='social-engineering'
union all select id,4,'Be skeptical of unsolicited requests for information, even if they seem to come from an authority figure.' from public.modules where slug='social-engineering';

-- Financial & Cryptocurrency Scams -----------------------------------------------
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,1,'The Rise of Crypto Scams','With the popularity of cryptocurrency, scammers have developed sophisticated methods to steal digital assets. Because crypto transactions are often irreversible, they are a prime target for fraudsters.','[]' from public.modules where slug='financial-crypto';
insert into public.lesson_sections(module_id,sort_order,title,bullets) select id,2,'Common Financial Scams','["Pig Butchering (Investment Scams): Scammers build a long-term relationship (often romantic or friendly) online, then convince the victim to invest in a fake crypto platform. They show fake profits to encourage larger investments before disappearing with the money.","Fake Exchanges & Wallets: Malicious apps or websites designed to look like legitimate crypto exchanges. Once you deposit funds or enter your seed phrase, your assets are stolen.","Tech Support & Refund Scams: Scammers claim you are owed a refund or your account is compromised, then guide you to transfer funds or grant remote access to your device.","Giveaway Scams: Fake social media posts from ''celebrities'' promising to double any crypto you send to their address."]' from public.modules where slug='financial-crypto';
insert into public.lesson_sections(module_id,sort_order,title,body,bullets) select id,3,'Protecting Your Assets','Never share your wallet''s seed phrase or private keys with anyone. Be extremely skeptical of ''guaranteed'' high returns or pressure to invest quickly. Only use well-known, established cryptocurrency exchanges and verify URLs carefully before logging in.','[]' from public.modules where slug='financial-crypto';

with m as (select id from public.modules where slug='financial-crypto')
insert into public.questions(module_id,content_key,sort_order,prompt,explanation,topic,points) select id,'pig-butchering',1,'Someone you met online a few months ago suggests you invest in a new crypto trading platform that guarantees a 20% weekly return. They even show you screenshots of their profits. What should you do?','This is a classic ''pig butchering'' investment scam. Scammers build trust over time and use fake platforms showing fabricated profits to lure victims into investing large sums of money.','Investment scams',250 from m
union all select id,'seed-phrase',2,'You receive an email from a popular crypto exchange saying your account needs verification and asks you to enter your 12-word seed phrase. What is the correct action?','Your seed phrase is the master key to your crypto wallet. Legitimate exchanges or support staff will never ask for it. Anyone asking for your seed phrase is trying to steal your funds.','Wallet security',250 from m
union all select id,'giveaway-scam',3,'A famous entrepreneur tweets that they are giving back to the community and will double any Bitcoin sent to a specific address. What is this?','Giveaway scams are very common on social media. Scammers often hack verified accounts or create convincing fake profiles to trick people into sending crypto, which is never returned.','Giveaway scams',250 from m;

insert into public.question_options(question_id,content_key,sort_order,label,is_correct)
select q.id, v.content_key, v.sort_order, v.label, v.is_correct from public.questions q join (values
(1,'small-investment',1,'Start with a small investment to test the waters.',false),(1,'ask-details',2,'Ask them for more details about how the platform works.',false),(1,'pig-butchering',3,'Recognize this as a likely ''pig butchering'' scam and cut off contact.',true),(1,'borrow-money',4,'Borrow money to maximize your potential returns.',false),
(2,'enter-it',1,'Enter the seed phrase to ensure your account isn''t locked.',false),(2,'ignore-email',2,'Ignore the email, as legitimate exchanges will NEVER ask for your seed phrase.',true),(2,'reply-why',3,'Reply to the email asking why they need it.',false),(2,'forward-friend',4,'Forward the email to a friend for advice.',false),
(3,'legit-giveaway',1,'A legitimate promotional giveaway.',false),(3,'giveaway-scam',2,'A common giveaway scam, often using compromised verified accounts.',true),(3,'smart-contract-test',3,'A smart contract testing phase.',false),(3,'investment-opportunity',4,'An exclusive investment opportunity.',false)
) as v(question_order,content_key,sort_order,label,is_correct) on q.sort_order=v.question_order join public.modules m on m.id=q.module_id and m.slug='financial-crypto';

insert into public.cheat_sheet_items(module_id,sort_order,body) select id,1,'Never share your crypto wallet''s seed phrase or private keys with anyone.' from public.modules where slug='financial-crypto'
union all select id,2,'Be highly skeptical of online acquaintances pushing ''guaranteed'' high-return investments.' from public.modules where slug='financial-crypto'
union all select id,3,'Legitimate tech support will never ask you to send cryptocurrency.' from public.modules where slug='financial-crypto'
union all select id,4,'If an offer sounds too good to be true (like doubling your money), it is a scam.' from public.modules where slug='financial-crypto';
